/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateTestimonialRouteImport } from './routes/create-testimonial'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate-dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LaunchKitsIndexRouteImport } from './routes/launch-kits/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as LearnNotFoundRouteImport } from './routes/learn/not-found'
import { Route as LearnNoSegmentsRouteImport } from './routes/learn/no-segments'
import { Route as LearnCourseCompletedRouteImport } from './routes/learn/course-completed'
import { Route as LearnAddRouteImport } from './routes/learn/add'
import { Route as LaunchKitsSlugRouteImport } from './routes/launch-kits/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsSlugRouteImport } from './routes/agents/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AdminConversionsRouteImport } from './routes/admin/conversions'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAffiliatesRouteImport } from './routes/admin/affiliates'
import { Route as AdminLaunchKitsIndexRouteImport } from './routes/admin/launch-kits/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as LearnSlugEditRouteImport } from './routes/learn/$slug/edit'
import { Route as LearnSlugLayoutRouteImport } from './routes/learn/$slug/_layout'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as LearnSlugLayoutIndexRouteImport } from './routes/learn/$slug/_layout.index'
import { Route as AdminLaunchKitsCreateIndexRouteImport } from './routes/admin/launch-kits/create/index'
import { Route as AdminLaunchKitsEditIdRouteImport } from './routes/admin/launch-kits/edit/$id'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin/blog/$id/edit'
import { ServerRoute as ApiLogoutServerRouteImport } from './routes/api/logout'
import { ServerRoute as ApiStripeWebhookServerRouteImport } from './routes/api/stripe/webhook'
import { ServerRoute as ApiLoginGoogleIndexServerRouteImport } from './routes/api/login/google/index'
import { ServerRoute as ApiSegmentsSegmentIdVideoServerRouteImport } from './routes/api/segments/$segmentId/video'
import { ServerRoute as ApiLoginGoogleCallbackIndexServerRouteImport } from './routes/api/login/google/callback/index'

const LearnSlugRouteImport = createFileRoute('/learn/$slug')()
const rootServerRouteImport = createServerRootRoute()

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTestimonialRoute = CreateTestimonialRouteImport.update({
  id: '/create-testimonial',
  path: '/create-testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/affiliate-dashboard',
  path: '/affiliate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchKitsIndexRoute = LaunchKitsIndexRouteImport.update({
  id: '/launch-kits/',
  path: '/launch-kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNotFoundRoute = LearnNotFoundRouteImport.update({
  id: '/learn/not-found',
  path: '/learn/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNoSegmentsRoute = LearnNoSegmentsRouteImport.update({
  id: '/learn/no-segments',
  path: '/learn/no-segments',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseCompletedRoute = LearnCourseCompletedRouteImport.update({
  id: '/learn/course-completed',
  path: '/learn/course-completed',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAddRoute = LearnAddRouteImport.update({
  id: '/learn/add',
  path: '/learn/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchKitsSlugRoute = LaunchKitsSlugRouteImport.update({
  id: '/launch-kits/$slug',
  path: '/launch-kits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConversionsRoute = AdminConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLaunchKitsIndexRoute = AdminLaunchKitsIndexRouteImport.update({
  id: '/launch-kits/',
  path: '/launch-kits/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LearnSlugEditRoute = LearnSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LearnSlugRoute,
} as any)
const LearnSlugLayoutRoute = LearnSlugLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LearnSlugRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LearnSlugLayoutIndexRoute = LearnSlugLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnSlugLayoutRoute,
} as any)
const AdminLaunchKitsCreateIndexRoute =
  AdminLaunchKitsCreateIndexRouteImport.update({
    id: '/launch-kits/create/',
    path: '/launch-kits/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLaunchKitsEditIdRoute = AdminLaunchKitsEditIdRouteImport.update({
  id: '/launch-kits/edit/$id',
  path: '/launch-kits/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiLogoutServerRoute = ApiLogoutServerRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiStripeWebhookServerRoute = ApiStripeWebhookServerRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiLoginGoogleIndexServerRoute =
  ApiLoginGoogleIndexServerRouteImport.update({
    id: '/api/login/google/',
    path: '/api/login/google/',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiSegmentsSegmentIdVideoServerRoute =
  ApiSegmentsSegmentIdVideoServerRouteImport.update({
    id: '/api/segments/$segmentId/video',
    path: '/api/segments/$segmentId/video',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiLoginGoogleCallbackIndexServerRoute =
  ApiLoginGoogleCallbackIndexServerRouteImport.update({
    id: '/api/login/google/callback/',
    path: '/api/login/google/callback/',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliates': typeof AffiliatesRoute
  '/cancel': typeof CancelRoute
  '/community': typeof CommunityRoute
  '/create-testimonial': typeof CreateTestimonialRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/conversions': typeof AdminConversionsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/agents/new': typeof AgentsNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/launch-kits/$slug': typeof LaunchKitsSlugRoute
  '/learn/add': typeof LearnAddRoute
  '/learn/course-completed': typeof LearnCourseCompletedRoute
  '/learn/no-segments': typeof LearnNoSegmentsRoute
  '/learn/not-found': typeof LearnNotFoundRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/agents': typeof AgentsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/launch-kits': typeof LaunchKitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/learn/$slug': typeof LearnSlugLayoutRouteWithChildren
  '/learn/$slug/edit': typeof LearnSlugEditRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/launch-kits': typeof AdminLaunchKitsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/launch-kits/edit/$id': typeof AdminLaunchKitsEditIdRoute
  '/admin/launch-kits/create': typeof AdminLaunchKitsCreateIndexRoute
  '/learn/$slug/': typeof LearnSlugLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliates': typeof AffiliatesRoute
  '/cancel': typeof CancelRoute
  '/community': typeof CommunityRoute
  '/create-testimonial': typeof CreateTestimonialRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/conversions': typeof AdminConversionsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/agents/new': typeof AgentsNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/launch-kits/$slug': typeof LaunchKitsSlugRoute
  '/learn/add': typeof LearnAddRoute
  '/learn/course-completed': typeof LearnCourseCompletedRoute
  '/learn/no-segments': typeof LearnNoSegmentsRoute
  '/learn/not-found': typeof LearnNotFoundRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/agents': typeof AgentsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/launch-kits': typeof LaunchKitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/learn/$slug': typeof LearnSlugLayoutIndexRoute
  '/learn/$slug/edit': typeof LearnSlugEditRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/launch-kits': typeof AdminLaunchKitsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/launch-kits/edit/$id': typeof AdminLaunchKitsEditIdRoute
  '/admin/launch-kits/create': typeof AdminLaunchKitsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliates': typeof AffiliatesRoute
  '/cancel': typeof CancelRoute
  '/community': typeof CommunityRoute
  '/create-testimonial': typeof CreateTestimonialRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/conversions': typeof AdminConversionsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/agents/new': typeof AgentsNewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/launch-kits/$slug': typeof LaunchKitsSlugRoute
  '/learn/add': typeof LearnAddRoute
  '/learn/course-completed': typeof LearnCourseCompletedRoute
  '/learn/no-segments': typeof LearnNoSegmentsRoute
  '/learn/not-found': typeof LearnNotFoundRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/agents/': typeof AgentsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/launch-kits/': typeof LaunchKitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/learn/$slug': typeof LearnSlugRouteWithChildren
  '/learn/$slug/_layout': typeof LearnSlugLayoutRouteWithChildren
  '/learn/$slug/edit': typeof LearnSlugEditRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/launch-kits/': typeof AdminLaunchKitsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/launch-kits/edit/$id': typeof AdminLaunchKitsEditIdRoute
  '/admin/launch-kits/create/': typeof AdminLaunchKitsCreateIndexRoute
  '/learn/$slug/_layout/': typeof LearnSlugLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-dashboard'
    | '/affiliates'
    | '/cancel'
    | '/community'
    | '/create-testimonial'
    | '/login'
    | '/privacy-policy'
    | '/purchase'
    | '/settings'
    | '/success'
    | '/terms-of-service'
    | '/unauthenticated'
    | '/unauthorized'
    | '/unsubscribe'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/conversions'
    | '/admin/emails'
    | '/admin/settings'
    | '/admin/users'
    | '/agents/$slug'
    | '/agents/new'
    | '/blog/$slug'
    | '/launch-kits/$slug'
    | '/learn/add'
    | '/learn/course-completed'
    | '/learn/no-segments'
    | '/learn/not-found'
    | '/profile/$userId'
    | '/profile/edit'
    | '/agents'
    | '/blog'
    | '/launch-kits'
    | '/learn'
    | '/admin/blog/new'
    | '/learn/$slug'
    | '/learn/$slug/edit'
    | '/admin/blog'
    | '/admin/launch-kits'
    | '/admin/blog/$id/edit'
    | '/admin/launch-kits/edit/$id'
    | '/admin/launch-kits/create'
    | '/learn/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-dashboard'
    | '/affiliates'
    | '/cancel'
    | '/community'
    | '/create-testimonial'
    | '/login'
    | '/privacy-policy'
    | '/purchase'
    | '/settings'
    | '/success'
    | '/terms-of-service'
    | '/unauthenticated'
    | '/unauthorized'
    | '/unsubscribe'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/conversions'
    | '/admin/emails'
    | '/admin/settings'
    | '/admin/users'
    | '/agents/$slug'
    | '/agents/new'
    | '/blog/$slug'
    | '/launch-kits/$slug'
    | '/learn/add'
    | '/learn/course-completed'
    | '/learn/no-segments'
    | '/learn/not-found'
    | '/profile/$userId'
    | '/profile/edit'
    | '/agents'
    | '/blog'
    | '/launch-kits'
    | '/learn'
    | '/admin/blog/new'
    | '/learn/$slug'
    | '/learn/$slug/edit'
    | '/admin/blog'
    | '/admin/launch-kits'
    | '/admin/blog/$id/edit'
    | '/admin/launch-kits/edit/$id'
    | '/admin/launch-kits/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-dashboard'
    | '/affiliates'
    | '/cancel'
    | '/community'
    | '/create-testimonial'
    | '/login'
    | '/privacy-policy'
    | '/purchase'
    | '/settings'
    | '/success'
    | '/terms-of-service'
    | '/unauthenticated'
    | '/unauthorized'
    | '/unsubscribe'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/conversions'
    | '/admin/emails'
    | '/admin/settings'
    | '/admin/users'
    | '/agents/$slug'
    | '/agents/new'
    | '/blog/$slug'
    | '/launch-kits/$slug'
    | '/learn/add'
    | '/learn/course-completed'
    | '/learn/no-segments'
    | '/learn/not-found'
    | '/profile/$userId'
    | '/profile/edit'
    | '/agents/'
    | '/blog/'
    | '/launch-kits/'
    | '/learn/'
    | '/admin/blog/new'
    | '/learn/$slug'
    | '/learn/$slug/_layout'
    | '/learn/$slug/edit'
    | '/admin/blog/'
    | '/admin/launch-kits/'
    | '/admin/blog/$id/edit'
    | '/admin/launch-kits/edit/$id'
    | '/admin/launch-kits/create/'
    | '/learn/$slug/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AffiliatesRoute: typeof AffiliatesRoute
  CancelRoute: typeof CancelRoute
  CommunityRoute: typeof CommunityRoute
  CreateTestimonialRoute: typeof CreateTestimonialRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PurchaseRoute: typeof PurchaseRoute
  SettingsRoute: typeof SettingsRoute
  SuccessRoute: typeof SuccessRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  AgentsNewRoute: typeof AgentsNewRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LaunchKitsSlugRoute: typeof LaunchKitsSlugRoute
  LearnAddRoute: typeof LearnAddRoute
  LearnCourseCompletedRoute: typeof LearnCourseCompletedRoute
  LearnNoSegmentsRoute: typeof LearnNoSegmentsRoute
  LearnNotFoundRoute: typeof LearnNotFoundRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LaunchKitsIndexRoute: typeof LaunchKitsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnSlugRoute: typeof LearnSlugRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/logout': typeof ApiLogoutServerRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookServerRoute
  '/api/segments/$segmentId/video': typeof ApiSegmentsSegmentIdVideoServerRoute
  '/api/login/google': typeof ApiLoginGoogleIndexServerRoute
  '/api/login/google/callback': typeof ApiLoginGoogleCallbackIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/logout': typeof ApiLogoutServerRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookServerRoute
  '/api/segments/$segmentId/video': typeof ApiSegmentsSegmentIdVideoServerRoute
  '/api/login/google': typeof ApiLoginGoogleIndexServerRoute
  '/api/login/google/callback': typeof ApiLoginGoogleCallbackIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/logout': typeof ApiLogoutServerRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookServerRoute
  '/api/segments/$segmentId/video': typeof ApiSegmentsSegmentIdVideoServerRoute
  '/api/login/google/': typeof ApiLoginGoogleIndexServerRoute
  '/api/login/google/callback/': typeof ApiLoginGoogleCallbackIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/logout'
    | '/api/stripe/webhook'
    | '/api/segments/$segmentId/video'
    | '/api/login/google'
    | '/api/login/google/callback'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/logout'
    | '/api/stripe/webhook'
    | '/api/segments/$segmentId/video'
    | '/api/login/google'
    | '/api/login/google/callback'
  id:
    | '__root__'
    | '/api/logout'
    | '/api/stripe/webhook'
    | '/api/segments/$segmentId/video'
    | '/api/login/google/'
    | '/api/login/google/callback/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiLogoutServerRoute: typeof ApiLogoutServerRoute
  ApiStripeWebhookServerRoute: typeof ApiStripeWebhookServerRoute
  ApiSegmentsSegmentIdVideoServerRoute: typeof ApiSegmentsSegmentIdVideoServerRoute
  ApiLoginGoogleIndexServerRoute: typeof ApiLoginGoogleIndexServerRoute
  ApiLoginGoogleCallbackIndexServerRoute: typeof ApiLoginGoogleCallbackIndexServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-testimonial': {
      id: '/create-testimonial'
      path: '/create-testimonial'
      fullPath: '/create-testimonial'
      preLoaderRoute: typeof CreateTestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-dashboard': {
      id: '/affiliate-dashboard'
      path: '/affiliate-dashboard'
      fullPath: '/affiliate-dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-kits/': {
      id: '/launch-kits/'
      path: '/launch-kits'
      fullPath: '/launch-kits'
      preLoaderRoute: typeof LaunchKitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/not-found': {
      id: '/learn/not-found'
      path: '/learn/not-found'
      fullPath: '/learn/not-found'
      preLoaderRoute: typeof LearnNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/no-segments': {
      id: '/learn/no-segments'
      path: '/learn/no-segments'
      fullPath: '/learn/no-segments'
      preLoaderRoute: typeof LearnNoSegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/course-completed': {
      id: '/learn/course-completed'
      path: '/learn/course-completed'
      fullPath: '/learn/course-completed'
      preLoaderRoute: typeof LearnCourseCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/add': {
      id: '/learn/add'
      path: '/learn/add'
      fullPath: '/learn/add'
      preLoaderRoute: typeof LearnAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-kits/$slug': {
      id: '/launch-kits/$slug'
      path: '/launch-kits/$slug'
      fullPath: '/launch-kits/$slug'
      preLoaderRoute: typeof LaunchKitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/conversions': {
      id: '/admin/conversions'
      path: '/conversions'
      fullPath: '/admin/conversions'
      preLoaderRoute: typeof AdminConversionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/launch-kits/': {
      id: '/admin/launch-kits/'
      path: '/launch-kits'
      fullPath: '/admin/launch-kits'
      preLoaderRoute: typeof AdminLaunchKitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/learn/$slug/edit': {
      id: '/learn/$slug/edit'
      path: '/edit'
      fullPath: '/learn/$slug/edit'
      preLoaderRoute: typeof LearnSlugEditRouteImport
      parentRoute: typeof LearnSlugRoute
    }
    '/learn/$slug/_layout': {
      id: '/learn/$slug/_layout'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugLayoutRouteImport
      parentRoute: typeof LearnSlugRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/learn/$slug/_layout/': {
      id: '/learn/$slug/_layout/'
      path: '/'
      fullPath: '/learn/$slug/'
      preLoaderRoute: typeof LearnSlugLayoutIndexRouteImport
      parentRoute: typeof LearnSlugLayoutRoute
    }
    '/admin/launch-kits/create/': {
      id: '/admin/launch-kits/create/'
      path: '/launch-kits/create'
      fullPath: '/admin/launch-kits/create'
      preLoaderRoute: typeof AdminLaunchKitsCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/launch-kits/edit/$id': {
      id: '/admin/launch-kits/edit/$id'
      path: '/launch-kits/edit/$id'
      fullPath: '/admin/launch-kits/edit/$id'
      preLoaderRoute: typeof AdminLaunchKitsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/login/google/': {
      id: '/api/login/google/'
      path: '/api/login/google'
      fullPath: '/api/login/google'
      preLoaderRoute: typeof ApiLoginGoogleIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/segments/$segmentId/video': {
      id: '/api/segments/$segmentId/video'
      path: '/api/segments/$segmentId/video'
      fullPath: '/api/segments/$segmentId/video'
      preLoaderRoute: typeof ApiSegmentsSegmentIdVideoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/login/google/callback/': {
      id: '/api/login/google/callback/'
      path: '/api/login/google/callback'
      fullPath: '/api/login/google/callback'
      preLoaderRoute: typeof ApiLoginGoogleCallbackIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminConversionsRoute: typeof AdminConversionsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminLaunchKitsIndexRoute: typeof AdminLaunchKitsIndexRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
  AdminLaunchKitsEditIdRoute: typeof AdminLaunchKitsEditIdRoute
  AdminLaunchKitsCreateIndexRoute: typeof AdminLaunchKitsCreateIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminConversionsRoute: AdminConversionsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminLaunchKitsIndexRoute: AdminLaunchKitsIndexRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
  AdminLaunchKitsEditIdRoute: AdminLaunchKitsEditIdRoute,
  AdminLaunchKitsCreateIndexRoute: AdminLaunchKitsCreateIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LearnSlugLayoutRouteChildren {
  LearnSlugLayoutIndexRoute: typeof LearnSlugLayoutIndexRoute
}

const LearnSlugLayoutRouteChildren: LearnSlugLayoutRouteChildren = {
  LearnSlugLayoutIndexRoute: LearnSlugLayoutIndexRoute,
}

const LearnSlugLayoutRouteWithChildren = LearnSlugLayoutRoute._addFileChildren(
  LearnSlugLayoutRouteChildren,
)

interface LearnSlugRouteChildren {
  LearnSlugLayoutRoute: typeof LearnSlugLayoutRouteWithChildren
  LearnSlugEditRoute: typeof LearnSlugEditRoute
}

const LearnSlugRouteChildren: LearnSlugRouteChildren = {
  LearnSlugLayoutRoute: LearnSlugLayoutRouteWithChildren,
  LearnSlugEditRoute: LearnSlugEditRoute,
}

const LearnSlugRouteWithChildren = LearnSlugRoute._addFileChildren(
  LearnSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AffiliatesRoute: AffiliatesRoute,
  CancelRoute: CancelRoute,
  CommunityRoute: CommunityRoute,
  CreateTestimonialRoute: CreateTestimonialRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PurchaseRoute: PurchaseRoute,
  SettingsRoute: SettingsRoute,
  SuccessRoute: SuccessRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  AgentsNewRoute: AgentsNewRoute,
  BlogSlugRoute: BlogSlugRoute,
  LaunchKitsSlugRoute: LaunchKitsSlugRoute,
  LearnAddRoute: LearnAddRoute,
  LearnCourseCompletedRoute: LearnCourseCompletedRoute,
  LearnNoSegmentsRoute: LearnNoSegmentsRoute,
  LearnNotFoundRoute: LearnNotFoundRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  LaunchKitsIndexRoute: LaunchKitsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnSlugRoute: LearnSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiLogoutServerRoute: ApiLogoutServerRoute,
  ApiStripeWebhookServerRoute: ApiStripeWebhookServerRoute,
  ApiSegmentsSegmentIdVideoServerRoute: ApiSegmentsSegmentIdVideoServerRoute,
  ApiLoginGoogleIndexServerRoute: ApiLoginGoogleIndexServerRoute,
  ApiLoginGoogleCallbackIndexServerRoute:
    ApiLoginGoogleCallbackIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
