/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as CreateTestimonialRouteImport } from './routes/create-testimonial'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate-dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LaunchKitsIndexRouteImport } from './routes/launch-kits/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as LearnNotFoundRouteImport } from './routes/learn/not-found'
import { Route as LearnNoSegmentsRouteImport } from './routes/learn/no-segments'
import { Route as LearnCourseCompletedRouteImport } from './routes/learn/course-completed'
import { Route as LearnAddRouteImport } from './routes/learn/add'
import { Route as LaunchKitsSlugRouteImport } from './routes/launch-kits/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsSlugRouteImport } from './routes/agents/$slug'
import { Route as AdminVideoProcessingRouteImport } from './routes/admin/video-processing'
import { Route as AdminUtmAnalyticsRouteImport } from './routes/admin/utm-analytics'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAffiliatesRouteImport } from './routes/admin/affiliates'
import { Route as AdminEmailsRouteRouteImport } from './routes/admin/emails/route'
import { Route as AdminConversionsRouteRouteImport } from './routes/admin/conversions/route'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminLaunchKitsIndexRouteImport } from './routes/admin/launch-kits/index'
import { Route as AdminEmailsIndexRouteImport } from './routes/admin/emails/index'
import { Route as AdminConversionsIndexRouteImport } from './routes/admin/conversions/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as LearnSlugEditRouteImport } from './routes/learn/$slug/edit'
import { Route as LearnSlugLayoutRouteImport } from './routes/learn/$slug/_layout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AdminNewsNewRouteImport } from './routes/admin/news/new'
import { Route as AdminLaunchKitsTagsRouteImport } from './routes/admin/launch-kits/tags'
import { Route as AdminEmailsWaitlistRouteImport } from './routes/admin/emails/waitlist'
import { Route as AdminEmailsSegmentsRouteImport } from './routes/admin/emails/segments'
import { Route as AdminEmailsHistoryRouteImport } from './routes/admin/emails/history'
import { Route as AdminEmailsComposeRouteImport } from './routes/admin/emails/compose'
import { Route as AdminEmailsAnalyticsRouteImport } from './routes/admin/emails/analytics'
import { Route as AdminConversionsPagesRouteImport } from './routes/admin/conversions/pages'
import { Route as AdminConversionsOverviewRouteImport } from './routes/admin/conversions/overview'
import { Route as AdminConversionsEventsRouteImport } from './routes/admin/conversions/events'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as LearnSlugLayoutIndexRouteImport } from './routes/learn/$slug/_layout.index'
import { Route as ApiLoginGoogleIndexRouteImport } from './routes/api/login/google/index'
import { Route as AdminLaunchKitsCreateIndexRouteImport } from './routes/admin/launch-kits/create/index'
import { Route as ApiSegmentsSegmentIdVideoRouteImport } from './routes/api/segments/$segmentId/video'
import { Route as AdminNewsIdEditRouteImport } from './routes/admin/news/$id/edit'
import { Route as AdminLaunchKitsEditIdRouteImport } from './routes/admin/launch-kits/edit/$id'
import { Route as AdminBlogIdEditRouteImport } from './routes/admin/blog/$id/edit'
import { Route as ApiLoginGoogleCallbackIndexRouteImport } from './routes/api/login/google/callback/index'

const LearnSlugRouteImport = createFileRoute('/learn/$slug')()

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTestimonialRoute = CreateTestimonialRouteImport.update({
  id: '/create-testimonial',
  path: '/create-testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/affiliate-dashboard',
  path: '/affiliate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchKitsIndexRoute = LaunchKitsIndexRouteImport.update({
  id: '/launch-kits/',
  path: '/launch-kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNotFoundRoute = LearnNotFoundRouteImport.update({
  id: '/learn/not-found',
  path: '/learn/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnNoSegmentsRoute = LearnNoSegmentsRouteImport.update({
  id: '/learn/no-segments',
  path: '/learn/no-segments',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseCompletedRoute = LearnCourseCompletedRouteImport.update({
  id: '/learn/course-completed',
  path: '/learn/course-completed',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAddRoute = LearnAddRouteImport.update({
  id: '/learn/add',
  path: '/learn/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchKitsSlugRoute = LaunchKitsSlugRouteImport.update({
  id: '/launch-kits/$slug',
  path: '/launch-kits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoProcessingRoute = AdminVideoProcessingRouteImport.update({
  id: '/video-processing',
  path: '/video-processing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtmAnalyticsRoute = AdminUtmAnalyticsRouteImport.update({
  id: '/utm-analytics',
  path: '/utm-analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsRouteRoute = AdminEmailsRouteRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConversionsRouteRoute = AdminConversionsRouteRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLaunchKitsIndexRoute = AdminLaunchKitsIndexRouteImport.update({
  id: '/launch-kits/',
  path: '/launch-kits/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsIndexRoute = AdminEmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmailsRouteRoute,
} as any)
const AdminConversionsIndexRoute = AdminConversionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConversionsRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LearnSlugEditRoute = LearnSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LearnSlugRoute,
} as any)
const LearnSlugLayoutRoute = LearnSlugLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LearnSlugRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLaunchKitsTagsRoute = AdminLaunchKitsTagsRouteImport.update({
  id: '/launch-kits/tags',
  path: '/launch-kits/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsWaitlistRoute = AdminEmailsWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminEmailsRouteRoute,
} as any)
const AdminEmailsSegmentsRoute = AdminEmailsSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminEmailsRouteRoute,
} as any)
const AdminEmailsHistoryRoute = AdminEmailsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminEmailsRouteRoute,
} as any)
const AdminEmailsComposeRoute = AdminEmailsComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AdminEmailsRouteRoute,
} as any)
const AdminEmailsAnalyticsRoute = AdminEmailsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminEmailsRouteRoute,
} as any)
const AdminConversionsPagesRoute = AdminConversionsPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminConversionsRouteRoute,
} as any)
const AdminConversionsOverviewRoute =
  AdminConversionsOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AdminConversionsRouteRoute,
  } as any)
const AdminConversionsEventsRoute = AdminConversionsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminConversionsRouteRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LearnSlugLayoutIndexRoute = LearnSlugLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnSlugLayoutRoute,
} as any)
const ApiLoginGoogleIndexRoute = ApiLoginGoogleIndexRouteImport.update({
  id: '/api/login/google/',
  path: '/api/login/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLaunchKitsCreateIndexRoute =
  AdminLaunchKitsCreateIndexRouteImport.update({
    id: '/launch-kits/create/',
    path: '/launch-kits/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ApiSegmentsSegmentIdVideoRoute =
  ApiSegmentsSegmentIdVideoRouteImport.update({
    id: '/api/segments/$segmentId/video',
    path: '/api/segments/$segmentId/video',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewsIdEditRoute = AdminNewsIdEditRouteImport.update({
  id: '/news/$id/edit',
  path: '/news/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLaunchKitsEditIdRoute = AdminLaunchKitsEditIdRouteImport.update({
  id: '/launch-kits/edit/$id',
  path: '/launch-kits/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogIdEditRoute = AdminBlogIdEditRouteImport.update({
  id: '/blog/$id/edit',
  path: '/blog/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiLoginGoogleCallbackIndexRoute =
  ApiLoginGoogleCallbackIndexRouteImport.update({
    id: '/api/login/google/callback/',
    path: '/api/login/google/callback/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliates': typeof AffiliatesRoute
  '/cancel': typeof CancelRoute
  '/community': typeof CommunityRoute
  '/create-testimonial': typeof CreateTestimonialRoute
  '/dev-login': typeof DevLoginRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/conversions': typeof AdminConversionsRouteRouteWithChildren
  '/admin/emails': typeof AdminEmailsRouteRouteWithChildren
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/utm-analytics': typeof AdminUtmAnalyticsRoute
  '/admin/video-processing': typeof AdminVideoProcessingRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/health': typeof ApiHealthRoute
  '/api/logout': typeof ApiLogoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/launch-kits/$slug': typeof LaunchKitsSlugRoute
  '/learn/add': typeof LearnAddRoute
  '/learn/course-completed': typeof LearnCourseCompletedRoute
  '/learn/no-segments': typeof LearnNoSegmentsRoute
  '/learn/not-found': typeof LearnNotFoundRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/agents': typeof AgentsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/launch-kits': typeof LaunchKitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/conversions/events': typeof AdminConversionsEventsRoute
  '/admin/conversions/overview': typeof AdminConversionsOverviewRoute
  '/admin/conversions/pages': typeof AdminConversionsPagesRoute
  '/admin/emails/analytics': typeof AdminEmailsAnalyticsRoute
  '/admin/emails/compose': typeof AdminEmailsComposeRoute
  '/admin/emails/history': typeof AdminEmailsHistoryRoute
  '/admin/emails/segments': typeof AdminEmailsSegmentsRoute
  '/admin/emails/waitlist': typeof AdminEmailsWaitlistRoute
  '/admin/launch-kits/tags': typeof AdminLaunchKitsTagsRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/learn/$slug': typeof LearnSlugLayoutRouteWithChildren
  '/learn/$slug/edit': typeof LearnSlugEditRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/conversions/': typeof AdminConversionsIndexRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/admin/launch-kits': typeof AdminLaunchKitsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/launch-kits/edit/$id': typeof AdminLaunchKitsEditIdRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/api/segments/$segmentId/video': typeof ApiSegmentsSegmentIdVideoRoute
  '/admin/launch-kits/create': typeof AdminLaunchKitsCreateIndexRoute
  '/api/login/google': typeof ApiLoginGoogleIndexRoute
  '/learn/$slug/': typeof LearnSlugLayoutIndexRoute
  '/api/login/google/callback': typeof ApiLoginGoogleCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliates': typeof AffiliatesRoute
  '/cancel': typeof CancelRoute
  '/community': typeof CommunityRoute
  '/create-testimonial': typeof CreateTestimonialRoute
  '/dev-login': typeof DevLoginRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/utm-analytics': typeof AdminUtmAnalyticsRoute
  '/admin/video-processing': typeof AdminVideoProcessingRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/health': typeof ApiHealthRoute
  '/api/logout': typeof ApiLogoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/launch-kits/$slug': typeof LaunchKitsSlugRoute
  '/learn/add': typeof LearnAddRoute
  '/learn/course-completed': typeof LearnCourseCompletedRoute
  '/learn/no-segments': typeof LearnNoSegmentsRoute
  '/learn/not-found': typeof LearnNotFoundRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/agents': typeof AgentsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/launch-kits': typeof LaunchKitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/conversions/events': typeof AdminConversionsEventsRoute
  '/admin/conversions/overview': typeof AdminConversionsOverviewRoute
  '/admin/conversions/pages': typeof AdminConversionsPagesRoute
  '/admin/emails/analytics': typeof AdminEmailsAnalyticsRoute
  '/admin/emails/compose': typeof AdminEmailsComposeRoute
  '/admin/emails/history': typeof AdminEmailsHistoryRoute
  '/admin/emails/segments': typeof AdminEmailsSegmentsRoute
  '/admin/emails/waitlist': typeof AdminEmailsWaitlistRoute
  '/admin/launch-kits/tags': typeof AdminLaunchKitsTagsRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/learn/$slug': typeof LearnSlugLayoutIndexRoute
  '/learn/$slug/edit': typeof LearnSlugEditRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/conversions': typeof AdminConversionsIndexRoute
  '/admin/emails': typeof AdminEmailsIndexRoute
  '/admin/launch-kits': typeof AdminLaunchKitsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/launch-kits/edit/$id': typeof AdminLaunchKitsEditIdRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/api/segments/$segmentId/video': typeof ApiSegmentsSegmentIdVideoRoute
  '/admin/launch-kits/create': typeof AdminLaunchKitsCreateIndexRoute
  '/api/login/google': typeof ApiLoginGoogleIndexRoute
  '/api/login/google/callback': typeof ApiLoginGoogleCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliates': typeof AffiliatesRoute
  '/cancel': typeof CancelRoute
  '/community': typeof CommunityRoute
  '/create-testimonial': typeof CreateTestimonialRoute
  '/dev-login': typeof DevLoginRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase': typeof PurchaseRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/success': typeof SuccessRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/conversions': typeof AdminConversionsRouteRouteWithChildren
  '/admin/emails': typeof AdminEmailsRouteRouteWithChildren
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/utm-analytics': typeof AdminUtmAnalyticsRoute
  '/admin/video-processing': typeof AdminVideoProcessingRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/health': typeof ApiHealthRoute
  '/api/logout': typeof ApiLogoutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/launch-kits/$slug': typeof LaunchKitsSlugRoute
  '/learn/add': typeof LearnAddRoute
  '/learn/course-completed': typeof LearnCourseCompletedRoute
  '/learn/no-segments': typeof LearnNoSegmentsRoute
  '/learn/not-found': typeof LearnNotFoundRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/agents/': typeof AgentsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/launch-kits/': typeof LaunchKitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/conversions/events': typeof AdminConversionsEventsRoute
  '/admin/conversions/overview': typeof AdminConversionsOverviewRoute
  '/admin/conversions/pages': typeof AdminConversionsPagesRoute
  '/admin/emails/analytics': typeof AdminEmailsAnalyticsRoute
  '/admin/emails/compose': typeof AdminEmailsComposeRoute
  '/admin/emails/history': typeof AdminEmailsHistoryRoute
  '/admin/emails/segments': typeof AdminEmailsSegmentsRoute
  '/admin/emails/waitlist': typeof AdminEmailsWaitlistRoute
  '/admin/launch-kits/tags': typeof AdminLaunchKitsTagsRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/learn/$slug': typeof LearnSlugRouteWithChildren
  '/learn/$slug/_layout': typeof LearnSlugLayoutRouteWithChildren
  '/learn/$slug/edit': typeof LearnSlugEditRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/conversions/': typeof AdminConversionsIndexRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/admin/launch-kits/': typeof AdminLaunchKitsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/blog/$id/edit': typeof AdminBlogIdEditRoute
  '/admin/launch-kits/edit/$id': typeof AdminLaunchKitsEditIdRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/api/segments/$segmentId/video': typeof ApiSegmentsSegmentIdVideoRoute
  '/admin/launch-kits/create/': typeof AdminLaunchKitsCreateIndexRoute
  '/api/login/google/': typeof ApiLoginGoogleIndexRoute
  '/learn/$slug/_layout/': typeof LearnSlugLayoutIndexRoute
  '/api/login/google/callback/': typeof ApiLoginGoogleCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-dashboard'
    | '/affiliates'
    | '/cancel'
    | '/community'
    | '/create-testimonial'
    | '/dev-login'
    | '/health'
    | '/login'
    | '/members'
    | '/news'
    | '/privacy-policy'
    | '/purchase'
    | '/refund-policy'
    | '/settings'
    | '/success'
    | '/terms-of-service'
    | '/unauthenticated'
    | '/unauthorized'
    | '/unsubscribe'
    | '/admin/conversions'
    | '/admin/emails'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/utm-analytics'
    | '/admin/video-processing'
    | '/agents/$slug'
    | '/agents/new'
    | '/api/health'
    | '/api/logout'
    | '/blog/$slug'
    | '/launch-kits/$slug'
    | '/learn/add'
    | '/learn/course-completed'
    | '/learn/no-segments'
    | '/learn/not-found'
    | '/profile/$userId'
    | '/profile/edit'
    | '/agents'
    | '/blog'
    | '/launch-kits'
    | '/learn'
    | '/admin/blog/new'
    | '/admin/conversions/events'
    | '/admin/conversions/overview'
    | '/admin/conversions/pages'
    | '/admin/emails/analytics'
    | '/admin/emails/compose'
    | '/admin/emails/history'
    | '/admin/emails/segments'
    | '/admin/emails/waitlist'
    | '/admin/launch-kits/tags'
    | '/admin/news/new'
    | '/api/stripe/webhook'
    | '/learn/$slug'
    | '/learn/$slug/edit'
    | '/admin/blog'
    | '/admin/conversions/'
    | '/admin/emails/'
    | '/admin/launch-kits'
    | '/admin/news'
    | '/admin/blog/$id/edit'
    | '/admin/launch-kits/edit/$id'
    | '/admin/news/$id/edit'
    | '/api/segments/$segmentId/video'
    | '/admin/launch-kits/create'
    | '/api/login/google'
    | '/learn/$slug/'
    | '/api/login/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-dashboard'
    | '/affiliates'
    | '/cancel'
    | '/community'
    | '/create-testimonial'
    | '/dev-login'
    | '/health'
    | '/login'
    | '/members'
    | '/news'
    | '/privacy-policy'
    | '/purchase'
    | '/refund-policy'
    | '/settings'
    | '/success'
    | '/terms-of-service'
    | '/unauthenticated'
    | '/unauthorized'
    | '/unsubscribe'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/utm-analytics'
    | '/admin/video-processing'
    | '/agents/$slug'
    | '/agents/new'
    | '/api/health'
    | '/api/logout'
    | '/blog/$slug'
    | '/launch-kits/$slug'
    | '/learn/add'
    | '/learn/course-completed'
    | '/learn/no-segments'
    | '/learn/not-found'
    | '/profile/$userId'
    | '/profile/edit'
    | '/agents'
    | '/blog'
    | '/launch-kits'
    | '/learn'
    | '/admin/blog/new'
    | '/admin/conversions/events'
    | '/admin/conversions/overview'
    | '/admin/conversions/pages'
    | '/admin/emails/analytics'
    | '/admin/emails/compose'
    | '/admin/emails/history'
    | '/admin/emails/segments'
    | '/admin/emails/waitlist'
    | '/admin/launch-kits/tags'
    | '/admin/news/new'
    | '/api/stripe/webhook'
    | '/learn/$slug'
    | '/learn/$slug/edit'
    | '/admin/blog'
    | '/admin/conversions'
    | '/admin/emails'
    | '/admin/launch-kits'
    | '/admin/news'
    | '/admin/blog/$id/edit'
    | '/admin/launch-kits/edit/$id'
    | '/admin/news/$id/edit'
    | '/api/segments/$segmentId/video'
    | '/admin/launch-kits/create'
    | '/api/login/google'
    | '/api/login/google/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-dashboard'
    | '/affiliates'
    | '/cancel'
    | '/community'
    | '/create-testimonial'
    | '/dev-login'
    | '/health'
    | '/login'
    | '/members'
    | '/news'
    | '/privacy-policy'
    | '/purchase'
    | '/refund-policy'
    | '/settings'
    | '/success'
    | '/terms-of-service'
    | '/unauthenticated'
    | '/unauthorized'
    | '/unsubscribe'
    | '/admin/conversions'
    | '/admin/emails'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/utm-analytics'
    | '/admin/video-processing'
    | '/agents/$slug'
    | '/agents/new'
    | '/api/health'
    | '/api/logout'
    | '/blog/$slug'
    | '/launch-kits/$slug'
    | '/learn/add'
    | '/learn/course-completed'
    | '/learn/no-segments'
    | '/learn/not-found'
    | '/profile/$userId'
    | '/profile/edit'
    | '/agents/'
    | '/blog/'
    | '/launch-kits/'
    | '/learn/'
    | '/admin/blog/new'
    | '/admin/conversions/events'
    | '/admin/conversions/overview'
    | '/admin/conversions/pages'
    | '/admin/emails/analytics'
    | '/admin/emails/compose'
    | '/admin/emails/history'
    | '/admin/emails/segments'
    | '/admin/emails/waitlist'
    | '/admin/launch-kits/tags'
    | '/admin/news/new'
    | '/api/stripe/webhook'
    | '/learn/$slug'
    | '/learn/$slug/_layout'
    | '/learn/$slug/edit'
    | '/admin/blog/'
    | '/admin/conversions/'
    | '/admin/emails/'
    | '/admin/launch-kits/'
    | '/admin/news/'
    | '/admin/blog/$id/edit'
    | '/admin/launch-kits/edit/$id'
    | '/admin/news/$id/edit'
    | '/api/segments/$segmentId/video'
    | '/admin/launch-kits/create/'
    | '/api/login/google/'
    | '/learn/$slug/_layout/'
    | '/api/login/google/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AffiliatesRoute: typeof AffiliatesRoute
  CancelRoute: typeof CancelRoute
  CommunityRoute: typeof CommunityRoute
  CreateTestimonialRoute: typeof CreateTestimonialRoute
  DevLoginRoute: typeof DevLoginRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PurchaseRoute: typeof PurchaseRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SettingsRoute: typeof SettingsRoute
  SuccessRoute: typeof SuccessRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  AgentsNewRoute: typeof AgentsNewRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LaunchKitsSlugRoute: typeof LaunchKitsSlugRoute
  LearnAddRoute: typeof LearnAddRoute
  LearnCourseCompletedRoute: typeof LearnCourseCompletedRoute
  LearnNoSegmentsRoute: typeof LearnNoSegmentsRoute
  LearnNotFoundRoute: typeof LearnNotFoundRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LaunchKitsIndexRoute: typeof LaunchKitsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LearnSlugRoute: typeof LearnSlugRouteWithChildren
  ApiSegmentsSegmentIdVideoRoute: typeof ApiSegmentsSegmentIdVideoRoute
  ApiLoginGoogleIndexRoute: typeof ApiLoginGoogleIndexRoute
  ApiLoginGoogleCallbackIndexRoute: typeof ApiLoginGoogleCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-testimonial': {
      id: '/create-testimonial'
      path: '/create-testimonial'
      fullPath: '/create-testimonial'
      preLoaderRoute: typeof CreateTestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-dashboard': {
      id: '/affiliate-dashboard'
      path: '/affiliate-dashboard'
      fullPath: '/affiliate-dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-kits/': {
      id: '/launch-kits/'
      path: '/launch-kits'
      fullPath: '/launch-kits'
      preLoaderRoute: typeof LaunchKitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/not-found': {
      id: '/learn/not-found'
      path: '/learn/not-found'
      fullPath: '/learn/not-found'
      preLoaderRoute: typeof LearnNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/no-segments': {
      id: '/learn/no-segments'
      path: '/learn/no-segments'
      fullPath: '/learn/no-segments'
      preLoaderRoute: typeof LearnNoSegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/course-completed': {
      id: '/learn/course-completed'
      path: '/learn/course-completed'
      fullPath: '/learn/course-completed'
      preLoaderRoute: typeof LearnCourseCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/add': {
      id: '/learn/add'
      path: '/learn/add'
      fullPath: '/learn/add'
      preLoaderRoute: typeof LearnAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-kits/$slug': {
      id: '/launch-kits/$slug'
      path: '/launch-kits/$slug'
      fullPath: '/launch-kits/$slug'
      preLoaderRoute: typeof LaunchKitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/video-processing': {
      id: '/admin/video-processing'
      path: '/video-processing'
      fullPath: '/admin/video-processing'
      preLoaderRoute: typeof AdminVideoProcessingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utm-analytics': {
      id: '/admin/utm-analytics'
      path: '/utm-analytics'
      fullPath: '/admin/utm-analytics'
      preLoaderRoute: typeof AdminUtmAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/conversions': {
      id: '/admin/conversions'
      path: '/conversions'
      fullPath: '/admin/conversions'
      preLoaderRoute: typeof AdminConversionsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/launch-kits/': {
      id: '/admin/launch-kits/'
      path: '/launch-kits'
      fullPath: '/admin/launch-kits'
      preLoaderRoute: typeof AdminLaunchKitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails/': {
      id: '/admin/emails/'
      path: '/'
      fullPath: '/admin/emails/'
      preLoaderRoute: typeof AdminEmailsIndexRouteImport
      parentRoute: typeof AdminEmailsRouteRoute
    }
    '/admin/conversions/': {
      id: '/admin/conversions/'
      path: '/'
      fullPath: '/admin/conversions/'
      preLoaderRoute: typeof AdminConversionsIndexRouteImport
      parentRoute: typeof AdminConversionsRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/learn/$slug/edit': {
      id: '/learn/$slug/edit'
      path: '/edit'
      fullPath: '/learn/$slug/edit'
      preLoaderRoute: typeof LearnSlugEditRouteImport
      parentRoute: typeof LearnSlugRoute
    }
    '/learn/$slug/_layout': {
      id: '/learn/$slug/_layout'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugLayoutRouteImport
      parentRoute: typeof LearnSlugRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/launch-kits/tags': {
      id: '/admin/launch-kits/tags'
      path: '/launch-kits/tags'
      fullPath: '/admin/launch-kits/tags'
      preLoaderRoute: typeof AdminLaunchKitsTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails/waitlist': {
      id: '/admin/emails/waitlist'
      path: '/waitlist'
      fullPath: '/admin/emails/waitlist'
      preLoaderRoute: typeof AdminEmailsWaitlistRouteImport
      parentRoute: typeof AdminEmailsRouteRoute
    }
    '/admin/emails/segments': {
      id: '/admin/emails/segments'
      path: '/segments'
      fullPath: '/admin/emails/segments'
      preLoaderRoute: typeof AdminEmailsSegmentsRouteImport
      parentRoute: typeof AdminEmailsRouteRoute
    }
    '/admin/emails/history': {
      id: '/admin/emails/history'
      path: '/history'
      fullPath: '/admin/emails/history'
      preLoaderRoute: typeof AdminEmailsHistoryRouteImport
      parentRoute: typeof AdminEmailsRouteRoute
    }
    '/admin/emails/compose': {
      id: '/admin/emails/compose'
      path: '/compose'
      fullPath: '/admin/emails/compose'
      preLoaderRoute: typeof AdminEmailsComposeRouteImport
      parentRoute: typeof AdminEmailsRouteRoute
    }
    '/admin/emails/analytics': {
      id: '/admin/emails/analytics'
      path: '/analytics'
      fullPath: '/admin/emails/analytics'
      preLoaderRoute: typeof AdminEmailsAnalyticsRouteImport
      parentRoute: typeof AdminEmailsRouteRoute
    }
    '/admin/conversions/pages': {
      id: '/admin/conversions/pages'
      path: '/pages'
      fullPath: '/admin/conversions/pages'
      preLoaderRoute: typeof AdminConversionsPagesRouteImport
      parentRoute: typeof AdminConversionsRouteRoute
    }
    '/admin/conversions/overview': {
      id: '/admin/conversions/overview'
      path: '/overview'
      fullPath: '/admin/conversions/overview'
      preLoaderRoute: typeof AdminConversionsOverviewRouteImport
      parentRoute: typeof AdminConversionsRouteRoute
    }
    '/admin/conversions/events': {
      id: '/admin/conversions/events'
      path: '/events'
      fullPath: '/admin/conversions/events'
      preLoaderRoute: typeof AdminConversionsEventsRouteImport
      parentRoute: typeof AdminConversionsRouteRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/learn/$slug/_layout/': {
      id: '/learn/$slug/_layout/'
      path: '/'
      fullPath: '/learn/$slug/'
      preLoaderRoute: typeof LearnSlugLayoutIndexRouteImport
      parentRoute: typeof LearnSlugLayoutRoute
    }
    '/api/login/google/': {
      id: '/api/login/google/'
      path: '/api/login/google'
      fullPath: '/api/login/google'
      preLoaderRoute: typeof ApiLoginGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/launch-kits/create/': {
      id: '/admin/launch-kits/create/'
      path: '/launch-kits/create'
      fullPath: '/admin/launch-kits/create'
      preLoaderRoute: typeof AdminLaunchKitsCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/segments/$segmentId/video': {
      id: '/api/segments/$segmentId/video'
      path: '/api/segments/$segmentId/video'
      fullPath: '/api/segments/$segmentId/video'
      preLoaderRoute: typeof ApiSegmentsSegmentIdVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/$id/edit': {
      id: '/admin/news/$id/edit'
      path: '/news/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminNewsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/launch-kits/edit/$id': {
      id: '/admin/launch-kits/edit/$id'
      path: '/launch-kits/edit/$id'
      fullPath: '/admin/launch-kits/edit/$id'
      preLoaderRoute: typeof AdminLaunchKitsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog/$id/edit': {
      id: '/admin/blog/$id/edit'
      path: '/blog/$id/edit'
      fullPath: '/admin/blog/$id/edit'
      preLoaderRoute: typeof AdminBlogIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/login/google/callback/': {
      id: '/api/login/google/callback/'
      path: '/api/login/google/callback'
      fullPath: '/api/login/google/callback'
      preLoaderRoute: typeof ApiLoginGoogleCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminConversionsRouteRouteChildren {
  AdminConversionsEventsRoute: typeof AdminConversionsEventsRoute
  AdminConversionsOverviewRoute: typeof AdminConversionsOverviewRoute
  AdminConversionsPagesRoute: typeof AdminConversionsPagesRoute
  AdminConversionsIndexRoute: typeof AdminConversionsIndexRoute
}

const AdminConversionsRouteRouteChildren: AdminConversionsRouteRouteChildren = {
  AdminConversionsEventsRoute: AdminConversionsEventsRoute,
  AdminConversionsOverviewRoute: AdminConversionsOverviewRoute,
  AdminConversionsPagesRoute: AdminConversionsPagesRoute,
  AdminConversionsIndexRoute: AdminConversionsIndexRoute,
}

const AdminConversionsRouteRouteWithChildren =
  AdminConversionsRouteRoute._addFileChildren(
    AdminConversionsRouteRouteChildren,
  )

interface AdminEmailsRouteRouteChildren {
  AdminEmailsAnalyticsRoute: typeof AdminEmailsAnalyticsRoute
  AdminEmailsComposeRoute: typeof AdminEmailsComposeRoute
  AdminEmailsHistoryRoute: typeof AdminEmailsHistoryRoute
  AdminEmailsSegmentsRoute: typeof AdminEmailsSegmentsRoute
  AdminEmailsWaitlistRoute: typeof AdminEmailsWaitlistRoute
  AdminEmailsIndexRoute: typeof AdminEmailsIndexRoute
}

const AdminEmailsRouteRouteChildren: AdminEmailsRouteRouteChildren = {
  AdminEmailsAnalyticsRoute: AdminEmailsAnalyticsRoute,
  AdminEmailsComposeRoute: AdminEmailsComposeRoute,
  AdminEmailsHistoryRoute: AdminEmailsHistoryRoute,
  AdminEmailsSegmentsRoute: AdminEmailsSegmentsRoute,
  AdminEmailsWaitlistRoute: AdminEmailsWaitlistRoute,
  AdminEmailsIndexRoute: AdminEmailsIndexRoute,
}

const AdminEmailsRouteRouteWithChildren =
  AdminEmailsRouteRoute._addFileChildren(AdminEmailsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminConversionsRouteRoute: typeof AdminConversionsRouteRouteWithChildren
  AdminEmailsRouteRoute: typeof AdminEmailsRouteRouteWithChildren
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminUtmAnalyticsRoute: typeof AdminUtmAnalyticsRoute
  AdminVideoProcessingRoute: typeof AdminVideoProcessingRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminLaunchKitsTagsRoute: typeof AdminLaunchKitsTagsRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminLaunchKitsIndexRoute: typeof AdminLaunchKitsIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminBlogIdEditRoute: typeof AdminBlogIdEditRoute
  AdminLaunchKitsEditIdRoute: typeof AdminLaunchKitsEditIdRoute
  AdminNewsIdEditRoute: typeof AdminNewsIdEditRoute
  AdminLaunchKitsCreateIndexRoute: typeof AdminLaunchKitsCreateIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConversionsRouteRoute: AdminConversionsRouteRouteWithChildren,
  AdminEmailsRouteRoute: AdminEmailsRouteRouteWithChildren,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminUtmAnalyticsRoute: AdminUtmAnalyticsRoute,
  AdminVideoProcessingRoute: AdminVideoProcessingRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminLaunchKitsTagsRoute: AdminLaunchKitsTagsRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminLaunchKitsIndexRoute: AdminLaunchKitsIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminBlogIdEditRoute: AdminBlogIdEditRoute,
  AdminLaunchKitsEditIdRoute: AdminLaunchKitsEditIdRoute,
  AdminNewsIdEditRoute: AdminNewsIdEditRoute,
  AdminLaunchKitsCreateIndexRoute: AdminLaunchKitsCreateIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface LearnSlugLayoutRouteChildren {
  LearnSlugLayoutIndexRoute: typeof LearnSlugLayoutIndexRoute
}

const LearnSlugLayoutRouteChildren: LearnSlugLayoutRouteChildren = {
  LearnSlugLayoutIndexRoute: LearnSlugLayoutIndexRoute,
}

const LearnSlugLayoutRouteWithChildren = LearnSlugLayoutRoute._addFileChildren(
  LearnSlugLayoutRouteChildren,
)

interface LearnSlugRouteChildren {
  LearnSlugLayoutRoute: typeof LearnSlugLayoutRouteWithChildren
  LearnSlugEditRoute: typeof LearnSlugEditRoute
}

const LearnSlugRouteChildren: LearnSlugRouteChildren = {
  LearnSlugLayoutRoute: LearnSlugLayoutRouteWithChildren,
  LearnSlugEditRoute: LearnSlugEditRoute,
}

const LearnSlugRouteWithChildren = LearnSlugRoute._addFileChildren(
  LearnSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AffiliatesRoute: AffiliatesRoute,
  CancelRoute: CancelRoute,
  CommunityRoute: CommunityRoute,
  CreateTestimonialRoute: CreateTestimonialRoute,
  DevLoginRoute: DevLoginRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PurchaseRoute: PurchaseRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SettingsRoute: SettingsRoute,
  SuccessRoute: SuccessRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  AgentsNewRoute: AgentsNewRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  BlogSlugRoute: BlogSlugRoute,
  LaunchKitsSlugRoute: LaunchKitsSlugRoute,
  LearnAddRoute: LearnAddRoute,
  LearnCourseCompletedRoute: LearnCourseCompletedRoute,
  LearnNoSegmentsRoute: LearnNoSegmentsRoute,
  LearnNotFoundRoute: LearnNotFoundRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  LaunchKitsIndexRoute: LaunchKitsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LearnSlugRoute: LearnSlugRouteWithChildren,
  ApiSegmentsSegmentIdVideoRoute: ApiSegmentsSegmentIdVideoRoute,
  ApiLoginGoogleIndexRoute: ApiLoginGoogleIndexRoute,
  ApiLoginGoogleCallbackIndexRoute: ApiLoginGoogleCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
